name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
      - documentation
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.9'
      - name: Install dependencies
        run: |
            julia --project=docs/ -e 'using Pkg; Pkg.Registry.update(); Pkg.develop(PackageSpec(path=pwd())); Pkg.add(["Documenter", "DocumenterCitations", "Literate", "CUDA", "MadNLP", "MadNLPGPU", "ExaModels", "Downloads"]); Pkg.instantiate()'
            julia --project=docs/ -e 'using Pkg; println("Installed packages: ", Pkg.installed())'
      - name: Verify environment
        run: julia --project=docs/ -e 'using Pkg; println("Environment setup successful!")'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=. docs/make.jl