name: Documentation

on:
  push:
    branches:
      - main # update to match your development branch (master, main, dev, trunk, ...)
    tags: '*'
  pull_request:

jobs:
  build:
    runs-on:
      labels: cuda
    strategy:
      matrix:
        julia-version: ['1']
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/install-juliaup@v2
        with:
          channel: ${{ matrix.julia-version }}
      - name: Cache Julia artifacts
        uses: actions/cache@v3
      - name: Instantiate the dependencies
        shell: julia --project=docs/ --color=yes {0}
        run: |
          using Pkg;
          Pkg.Registry.update();
          Pkg.instantiate();
      - name: Build and deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # If authenticating with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # If authenticating with SSH deploy key
        run: julia --project=docs/ --color=yes docs/make.jl
